require("greg.plugins.devicons")
require("greg.plugins.theme")
require("greg.plugins.neo-tree")
require("greg.plugins.telescope")
require("greg.plugins.lualine")
require("greg.plugins.snacks")
require("greg.plugins.lspconfig")
-- require("greg.plugins.fzf-lua")
-- require("greg.plugins.supermaven") -- Old supermaven import
require("greg.plugins.blink")
require("greg.plugins.treesitter")
require("greg.plugins.conform")
-- require("greg.plugins.avante")
require("greg.plugins.gitsigns")
require("greg.plugins.fugitive")
require("greg.plugins.nvim-lint")

-- Load plugins from the 'extra' directory
require("greg.plugins.extra.present")
require("greg.plugins.extra.trouble")
require("greg.plugins.extra.surround")
require("greg.plugins.extra.ts-autotag")
-- require("greg.plugins.extra.vim-visual-multi") -- Removed in favor of Neovim 0.13+ native multicursor
require("greg.plugins.extra.autopairs")
require("greg.plugins.extra.ts-comments")
require("greg.plugins.extra.cloak")
require("greg.plugins.extra.splitjoin")
require("greg.plugins.extra.which-key")
require("greg.plugins.extra.yanky")
require("greg.plugins.extra.supermaven")
require("greg.plugins.extra.oil")
require("greg.plugins.extra.rayso")
require("greg.plugins.extra.markdown-preview")
-- require("greg.plugins.smear")
-- require("greg.plugins.nvim-ufo")
-- require("greg.plugins.example")
