require("greg.plugins.devicons")
require("greg.plugins.theme")
require("greg.plugins.neo-tree")
require("greg.plugins.telescope")
require("greg.plugins.lualine")
require("greg.plugins.snacks")
require("greg.plugins.lspconfig")
-- require("greg.plugins.fzf-lua")
-- require("greg.plugins.supermaven") -- Old supermaven import
require("greg.plugins.blink")
require("greg.plugins.treesitter")
require("greg.plugins.conform")
-- require("greg.plugins.avante")
require("greg.plugins.gitsigns")
require("greg.plugins.fugitive")
require("greg.plugins.nvim-lint")

-- Load plugins from the 'extra' directory
require("greg.plugins.present")
require("greg.plugins.trouble")
require("greg.plugins.surround")
require("greg.plugins.ts-autotag")
-- require("greg.plugins.vim-visual-multi") -- Removed in favor of Neovim 0.13+ native multicursor
require("greg.plugins.autopairs")
require("greg.plugins.ts-comments")
require("greg.plugins.cloak")
require("greg.plugins.splitjoin")
require("greg.plugins.which-key")
require("greg.plugins.yanky")
require("greg.plugins.supermaven")
require("greg.plugins.oil")
require("greg.plugins.rayso")
require("greg.plugins.markdown-preview")
-- require("greg.plugins.smear")
-- require("greg.plugins.nvim-ufo")
-- require("greg.plugins.example")
