require("greg.packages.devicons")
require("greg.packages.theme")
require("greg.packages.neo-tree")
require("greg.packages.telescope")
require("greg.packages.lualine")
require("greg.packages.snacks")
require("greg.packages.lspconfig")
-- require("greg.packages.supermaven") -- Old supermaven import
require("greg.packages.blink")
require("greg.packages.treesitter")
require("greg.packages.conform")
require("greg.packages.dressing")
require("greg.packages.avante")
require("greg.packages.gitsigns")
require("greg.packages.fugitive")

-- Load plugins from the 'extra' directory
require("greg.packages.extra.present")
require("greg.packages.extra.undotree")
require("greg.packages.extra.trouble")
require("greg.packages.extra.surround")
require("greg.packages.extra.ts-autotag")
require("greg.packages.extra.vim-visual-multi")
require("greg.packages.extra.autopairs")
require("greg.packages.extra.ts-comments")
require("greg.packages.extra.cloak")
require("greg.packages.extra.splitjoin")
require("greg.packages.extra.which-key")
require("greg.packages.extra.yanky")
require("greg.packages.extra.supermaven")
require("greg.packages.extra.oil")
require("greg.packages.extra.rayso")
